package com.manoloycia.notificaciones.model;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import io.swagger.annotations.ApiModelProperty;

/**
 * Entity Notificacion: modelado en BDs
 * @author emruiz
 *
 */

@Entity
@Table(name = "notificacion")
public class Notificacion implements Serializable {
	
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

  //An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue
  @ApiModelProperty(notes = "The database generated product ID")
  private Long id;
  
  //Origen de la notificacion
  @ApiModelProperty(notes = "De", required = true)
  @NotNull
  @Column
  private String de;
  
  
  //Destinatario de la notificacion
  @ApiModelProperty(notes = "From: email/fax del destinatario de la notificación", required = true)
  @NotNull
  @Column
  private String para;
  
  //Estado de la notificacion
  @ApiModelProperty(notes = "Estado", required = true)
  @NotNull
  @Column
  private String estado;
  
  
  //Mensaje de la notificación
  @ApiModelProperty(notes = "Mensaje a enviar", required = true)
  @NotNull
  @Column
  private String mensaje;
  
  
  //Origen de la notificacion
  @ApiModelProperty(notes = "Fecha de Envio de la notificación", required = true)
  @Column
  @NotNull
  private Date fechaEnvio;
  
  //Tipo de Notificación: por Sms o Fax
  @ApiModelProperty(notes = "Tipo de notificación: SMS/FAX", required = true)
  @Column
  @NotNull
  private String tipoNotificacion;

  
  
    public Notificacion() {
    	super();
    }

	public Notificacion(Long id, String de, String para, String estado, String mensaje, Date fechaEnvio,
		String tipoNotificacion) {
		super();
		this.id = id;
		this.de = de;
		this.para = para;
		this.estado = estado;
		this.mensaje = mensaje;
		this.fechaEnvio = fechaEnvio;
		this.tipoNotificacion = tipoNotificacion;
    }

	public Notificacion(String de2, String para2, String estado2, String mensaje2, Date fechaEnvio2,
			String tipoNotificacion2) {
		super();
		this.de = de2;
		this.para = para2;
		this.estado = estado2;
		this.mensaje = mensaje2;
		this.fechaEnvio = fechaEnvio2;
		this.tipoNotificacion = tipoNotificacion2;
	}

	public Long  getId() {
		return id;
	}
	
	
	public void setId(Long id) {
		this.id = id;
	}
	
	
	public String getDe() {
		return de;
	}
	
	
	public void setDe(String de) {
		this.de = de;
	}
	
	
	public String getPara() {
		return para;
	}

	public void setPara(String para) {
		this.para = para;
	}

	public String getEstado() {
		return estado;
	}
	
	
	public void setEstado(String estado) {
		this.estado = estado;
	}
	
	
	public String getMensaje() {
		return mensaje;
	}
	
	
	public void setMensaje(String mensaje) {
		this.mensaje = mensaje;
	}
	
	
	public Date getFechaEnvio() {
		return fechaEnvio;
	}
	
	
	public void setFechaEnvio(Date fechaEnvio) {
		this.fechaEnvio = fechaEnvio;
	}
	
	
	public String getTipoNotificacion() {
		return tipoNotificacion;
	}
	
	
	public void setTipoNotificacion(String tipoNotificacion) {
		this.tipoNotificacion = tipoNotificacion;
	}


	@Override
	public String toString() {
		return "NotificacionDAO [id=" + id + ", de=" + de + ", para=" + para + ", estado=" + estado + ", mensaje="
				+ mensaje + ", fechaEnvio=" + fechaEnvio + ", tipoNotificacion=" + tipoNotificacion + "]";
	}
	
	

}
